# Generated by Django 6.0 on 2025-12-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value_string', models.CharField(blank=True, max_length=500, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='profiles.identityprofile')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contexts.valuetype')),
            ],
            options={
                'unique_together': {('profile', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AttributeContextRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contexts.context')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contexts.priorityrule')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_rules', to='attributes.profileattribute')),
            ],
            options={
                'unique_together': {('attribute', 'context')},
            },
        ),
    ]
