# Generated by Django 6.0 on 2026-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileattribute',
            name='value_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
