# Generated by Django 6.0 on 2026-03-05 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_profileattribute_value_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DEFAULT', 'Default'), ('OVERRIDE', 'Override'), ('FALLBACK', 'Fallback')], default='DEFAULT', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STRING', 'String'), ('DATE', 'Date'), ('INT', 'Integer'), ('URL', 'URL'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=30, unique=True)),
            ],
        ),
    ]
