# Generated by Django 6.0 on 2026-03-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_repopulate_and_remap_value_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecontextrule',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attributes.priorityrule'),
        ),
        migrations.AlterField(
            model_name='profileattribute',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attributes.valuetype'),
        ),
    ]
