# Generated by Django 6.0 on 2026-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_identityprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
