# Generated by Django 6.0 on 2026-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(choices=[('LEGAL', 'Legal'), ('PROFESSIONAL', 'Professional'), ('SOCIAL', 'Social'), ('CULTURAL', 'Cultural'), ('ONLINE', 'Online'), ('POLITICAL', 'Political'), ('RELIGIOUS', 'Religious/Spiritual'), ('ECONOMIC', 'Economic'), ('EDUCATIONAL', 'Educational/Academic'), ('FAMILIAL', 'Familial'), ('GENDER', 'Gender'), ('ETHNIC', 'Ethnic/Racial'), ('NATIONAL', 'National/Regional'), ('HEALTH', 'Health/Disability'), ('DIGITAL', 'Digital/Technological')], default='LEGAL', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='priorityrule',
            name='name',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('OVERRIDE', 'Override'), ('FALLBACK', 'Fallback')], default='DEFAULT', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='valuetype',
            name='name',
            field=models.CharField(choices=[('STRING', 'String'), ('DATE', 'Date'), ('INT', 'Integer'), ('URL', 'URL'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=30, unique=True),
        ),
    ]
