# Generated by Django 6.0 on 2026-02-26 12:22

from django.db import migrations

def populate_fixed_data(apps, schema_editor):
    # Get the models from the apps registry
    Context = apps.get_model('contexts', 'Context')
    PriorityRule = apps.get_model('contexts', 'PriorityRule')
    ValueType = apps.get_model('contexts', 'ValueType')

    # 1. Create Contexts using the Types inner class
    # Note: When using 'apps.get_model', we can't access the '.Types' class directly 
    # as a property, so we list the database values explicitly.
    contexts = [
        'LEGAL', 'PROFESSIONAL', 'SOCIAL', 'CULTURAL', 'ONLINE', 
        'POLITICAL', 'RELIGIOUS', 'ECONOMIC', 'EDUCATIONAL', 'FAMILIAL', 
        'GENDER', 'ETHNIC', 'NATIONAL', 'HEALTH', 'DIGITAL'
    ]
    for name in contexts:
        Context.objects.get_or_create(name=name)

    # 2. Create Priority Rules
    priority_rules = ['DEFAULT', 'OVERRIDE', 'FALLBACK']
    for name in priority_rules:
        PriorityRule.objects.get_or_create(name=name)

    # 3. Create Value Types
    value_types = ['STRING', 'DATE', 'INT', 'URL', 'BOOLEAN']
    for name in value_types:
        ValueType.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0002_alter_context_name_alter_priorityrule_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_fixed_data),
    ]
