# Generated by Django 6.0 on 2026-03-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_priorityrule_valuetype_and_more'),
        ('contexts', '0003_auto_20260226_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityRule',
        ),
        migrations.DeleteModel(
            name='ValueType',
        ),
    ]
